// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.11.4
// source: example.proto

package giorpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Giorpc_Encode_FullMethodName = "/giorpc.Giorpc/Encode"
	Giorpc_Decode_FullMethodName = "/giorpc.Giorpc/Decode"
)

// GiorpcClient is the client API for Giorpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GiorpcClient interface {
	Encode(ctx context.Context, in *EncodeRequest, opts ...grpc.CallOption) (*EncodeResponse, error)
	Decode(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (*DecodeResponse, error)
}

type giorpcClient struct {
	cc grpc.ClientConnInterface
}

func NewGiorpcClient(cc grpc.ClientConnInterface) GiorpcClient {
	return &giorpcClient{cc}
}

func (c *giorpcClient) Encode(ctx context.Context, in *EncodeRequest, opts ...grpc.CallOption) (*EncodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncodeResponse)
	err := c.cc.Invoke(ctx, Giorpc_Encode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giorpcClient) Decode(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (*DecodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecodeResponse)
	err := c.cc.Invoke(ctx, Giorpc_Decode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GiorpcServer is the server API for Giorpc service.
// All implementations must embed UnimplementedGiorpcServer
// for forward compatibility.
type GiorpcServer interface {
	Encode(context.Context, *EncodeRequest) (*EncodeResponse, error)
	Decode(context.Context, *DecodeRequest) (*DecodeResponse, error)
	mustEmbedUnimplementedGiorpcServer()
}

// UnimplementedGiorpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGiorpcServer struct{}

func (UnimplementedGiorpcServer) Encode(context.Context, *EncodeRequest) (*EncodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Encode not implemented")
}
func (UnimplementedGiorpcServer) Decode(context.Context, *DecodeRequest) (*DecodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decode not implemented")
}
func (UnimplementedGiorpcServer) mustEmbedUnimplementedGiorpcServer() {}
func (UnimplementedGiorpcServer) testEmbeddedByValue()                {}

// UnsafeGiorpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GiorpcServer will
// result in compilation errors.
type UnsafeGiorpcServer interface {
	mustEmbedUnimplementedGiorpcServer()
}

func RegisterGiorpcServer(s grpc.ServiceRegistrar, srv GiorpcServer) {
	// If the following call pancis, it indicates UnimplementedGiorpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Giorpc_ServiceDesc, srv)
}

func _Giorpc_Encode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiorpcServer).Encode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Giorpc_Encode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiorpcServer).Encode(ctx, req.(*EncodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Giorpc_Decode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiorpcServer).Decode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Giorpc_Decode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiorpcServer).Decode(ctx, req.(*DecodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Giorpc_ServiceDesc is the grpc.ServiceDesc for Giorpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Giorpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "giorpc.Giorpc",
	HandlerType: (*GiorpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encode",
			Handler:    _Giorpc_Encode_Handler,
		},
		{
			MethodName: "Decode",
			Handler:    _Giorpc_Decode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}
